### PR TITLE
Dform

### PR DESCRIPTION
**Pull request by snrelghgub**
hello team! plz have a look at the Donation form I created for our Donate Modal & give me your feedback (your suggestions for improvement is very welcome) Cheers

### CODE REVIEW

**Comment by ashiyaman** [comment]
The only thing I think is may be we can increase the height of item description textarea element. Rest  everything is good to go

**Comment by DrewDen** [comment]
Team, 
We are getting conflicts because we are not merging properly.  When we start a new branch we need to make sure we merge the develop branch code to it. This needs to be done before a pull request happens.  Then we can merge the new branch code to the develop branch because all the code will be up to date.  By simply creating a new branch and not pulling in any new code into it from the develop branch you could be writing over the code that is not showing because it is in the develop branch, not the new branch created.  Then when you go to merge the two branches together you get a conflict because the code is not the same.

**Comment by snrelghgub** [comment]
Thanks for your input ashiya. I agree that it has to be higher & I have just made the necessary changes.  Cheers

**Comment by snrelghgub** [comment]
hi Andrew, would you like to provide any suggestions for improvements in terms of content presentation of our donation form apart from your concerns regarding merge conflicts before I merge into our develop branch?

**Pull request merged**
