### PR TITLE
Header issue in mobile view 

### PR DESCRIPTION
**Pull request by DrewDen**
Team,
An issue came up that the two headers on how it works and contact us was not matching up to the about us in the mobile view.  Looking through the code I notice that the about us element was set to an H2.  How it works and contact us is set to H1.  In the media query, it is set for all H2 to resize the font.  

-fixed by simply changing the H1 to an H2.

### CODE REVIEW

**Comment by ashiyaman** [comment]
Thanks Andrew. I think all the headers should be h2.

**Comment by snrelghgub** [comment]
I checked out into your branch & had a look, it looks completely fine but ashiya made a good point. it'd be better if all the headers were h2 (I'm talking about the headers in the Donate & Find modals - they are too big in mobile view too). I changed them & committed the changes into your branch already, please don't be offended that I touched & worked on your branch lol - I did the changes as they are small & I was already in your branch so I thought I'd just change them while the code was already opened & already there in front of me. If you are happy with the changes too, Feel free to go ahead & merge to our Develop branch - you have my fullest approval!

**Comment by DrewDen** [comment]
I have no issues with you working on this branch.  Thank you for pointing out those changes in the two modals that also needed change.

**Comment by DrewDen** [comment]
ashiyaman thank you also for pointing that out.

**Comment by DrewDen** [comment]
Team,
I had to remove two of the last commits I made on this branch.  The recent commit I made was to fix all h1 headers into h2.  I decide to do this because I wanted to do things by our development workflow as agreed on.  The changes should show and everything should be good to go to merge in the develop branch.

**Pull request closed without merging**
